DND/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('wiki/', include('wiki.urls')),
    path('board/', include('board.urls')),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'users'
urlpatterns = [
    path('', views.main, name='main'),
    # Register page
    path('register/', views.register, name='register'),
    # Login page
    path('login/', views.logon, name='login'),
    # Logout page
    path('logout/', LogoutView.as_view(), name='logout'),
    # Profile page
    path('profile/', views.profile, name='profile')
]

wiki/urls.py
from django.urls import path
from . import views

app_name = 'wiki'
urlpatterns = [
    # Race
    path('races/', views.races, name='races'),
    # Beastiary
    path('bestiary/', views.bestiary, name='bestiary'),
    # Spells
    path('spells/', views.spells, name='spells'),
    # Items
    path('items/', views.items, name='items'),
    # Classes
    path('classes/', views.classes, name='classes'),
    # # Contents
    path('', views.content, name='content')

]

wiki/models.py
from django.db import models
from django.contrib.auth.models import User


class Base(models.Model):
    title = models.CharField(max_length=128)
    type = models.CharField(max_length=128)
    size = models.CharField(max_length=128)
    language = models.CharField(max_length=128)
    specials = models.CharField(max_length=128)
    armor_class = models.IntegerField(default=0)
    move_speed = models.IntegerField(default=30)


class Characteristics(models.Model):
    strength = models.IntegerField()
    agility = models.IntegerField()
    constitution = models.IntegerField()
    intelligence = models.IntegerField()
    wisdom = models.IntegerField()
    charisma = models.IntegerField()


class Actions(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField()


class Features(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField()


class Description(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField()


class RaceBestiary(models.Model):
    subclass_choice: list = [
        ('race', 'Игровая раса'),
        ('bestiary', 'Бестиарий')
    ]

    subclass = models.CharField(choices=subclass_choice, max_length=12)
    base = models.ForeignKey(Base, on_delete=models.CASCADE)
    characteristics = models.ForeignKey(Characteristics, on_delete=models.CASCADE)
    features = models.ForeignKey(Features, on_delete=models.CASCADE)
    actions = models.ForeignKey(Actions, on_delete=models.CASCADE)
    description = models.ForeignKey(Description, on_delete=models.CASCADE)


class Class(models.Model):
    title = models.CharField(max_length=128)


class Spell(models.Model):
    level = models.IntegerField()
    school = models.CharField(max_length=128)
    cast_time = models.CharField(max_length=128)
    distance = models.CharField(max_length=128)
    components = models.CharField(max_length=384)
    duration = models.CharField(max_length=128)
    classes = models.ManyToManyField(Class)


class Items(models.Model):
    field = models.ForeignKey(Description, on_delete=models.CASCADE)

wiki/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import *


@login_required()
def races(request):
    return render(request, 'wiki/races.html')


@login_required()
def bestiary(request):
    return render(request, 'wiki/bestiary.html')


@login_required()
def classes(request):
    return render(request, 'wiki/classes.html')


@login_required()
def items(request):
    return render(request, 'wiki/items.html')


@login_required()
def spells(request):
    return render(request, 'wiki/spells.html')


@login_required()
def content(request):
    return render(request, 'wiki/content.html')

wiki/templates/wiki/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>

    <meta charset="UTF-8">
    <title>DnD-Главная</title>
    <link rel="stylesheet" href="{% static 'wiki/css/contents.css' %}">
    <link rel="shortcut icon" href="/static/wiki/images/favicon.ico" type="image/x-icon">

</head>

<body>
    <div class="button_assist">
        <div class="left_field">
            <a class="button_nav" href="{% url 'wiki:content' %}">Главная</a>
            <a class="button_nav" href="{% url 'wiki:races' %}">Рассы</a>
            <a class="button_nav" href="{% url 'wiki:classes' %}">Классы</a>
            <a class="button_nav" href="{% url 'wiki:items' %}">Предметы</a>
            <a class="button_nav" href="{% url 'wiki:bestiary' %}">Бестиарий</a>
            <a class="button_nav" href="{% url 'wiki:spells' %}">Заклинания</a>
        </div>
    </div>
    <div class="text_field_wrap"></div>{% block content %}{% endblock content %}
<div class="right_field">
    <div class="nickname">{{ user.username }}</div>
    <a class="button_nav_right" href="{% url 'users:profile' %}">Профиль</a>
    <a class="button_nav_right" href="{% url 'wiki:races' %}">Справочник</a>
    <a class="button_nav_right" href="{% url 'users:logout' %}">Выход</a>
</div>
</body>
</html>

wiki/templates/wiki/classes.html
{%extends "wiki/base.html" %}
    {%block content%}
    <div class="text_field">
        <h1 style="text-align: center;">Классы</h1>
        <h2 style="text-align: center;">БАРД (Bard)</h2>
        Напевая, и перебирая пальцами по старинному монументу, найденному в заброшенных руинах, полуэльфийка в обветшалом кожаном доспехе перебирает знания, мелькающие в её голове, вызывая силой магии, заключённой в песне, людей, которые построили этот монумент
        и загадочное предание, которое он изображает.<br> Суровый человеческий воин ритмично ударяет своим мечом плашмя о доспех, задавая темп своего военного распева, вдохновляя спутников на отвагу и героизм. Магия его песни укрепляет и подбадривает
        их.
        <br> Смеясь, и настраивая свою цитру, девушка гном накладывает тонкую магию на собравшихся дворян, гарантируя, что слова её спутников будут хорошо восприняты. <br>
        <br> Неважно, кем является бард: учёным, скальдом или проходимцем; он плетёт магию из слов и музыки, вдохновляя союзников, деморализуя противников, манипулируя сознанием, создавая иллюзии, и даже исцеляя раны.<br>

        <h3 style="text-align: center;">Музыка и магия</h3><br> В мирах D&D слова и музыка это не просто колебания воздуха, тут они содержат в себе силу. И бард является мастером речей, песен, и волшебства, заложенного в них. Барды говорят, что вся мультивселенная была вызвана к существованию
        и сформирована словами, которые произнесли боги. И отражения этих первородных Слов Творения до сих пор звучат в космосе. Музыка бардов это попытка уловить эти отзвуки и тонко вплести их в свои заклинания.<br> Наиболее сильной чертой бардов является
        их исключительная разносторонность. Многие барды предпочитают держаться не на передовой в бою, используя свою магию для вдохновения союзников и препятствования противникам на расстоянии. Но барды способны защищать себя и в ближнем бою, при необходимости
        используя магию для укрепления своих клинков и доспехов. Их заклинания чаще предназначены для очарования и создания иллюзий, а не для создания явных разрушений. Они обладают обширными знаниями во множестве тематик и естественные способности, которые
        позволяют им делать хорошо практически всё. Барды становятся мастерами в тех талантах, к которым стремятся их умы, оттачивая их до совершенства, от музыкальных выступлений до эзотерических знаний.<br>

        <b style="text-align: center;">Обучение на опыте</b><br> Истинные барды не являются обыденной вещью в мире. Не каждый менестрель, поющий в таверне, или шут, скачущий при королевском дворе, является бардом. Чтобы обнаружить скрытую в музыке магию,
        требуется тяжёлое обучение и некоторая степень природного таланта, чего большинству трубадуров и жонглёров недостаёт. Однако, определить разницу между этими исполнителями может быть трудно. Жизнь барда проходит в странствиях по землям и посвящена
        сбору знаний, повествованию историй, и существованию за счёт благодарности публики, как и у любого другого артиста. Но глубина знаний, уровень музыкального мастерства и связь с магией ставит бардов на другую ступень от их собратьев.<br> Барды
        редко селятся надолго в одном месте, и их естественная тяга к странствиям связана с поиском новых сказаний, обучением новым навыкам и открытию новых горизонтов, что делает карьеру искателя приключений для них естественным призванием. Каждое приключение
        — это возможность чему-то научиться, попрактиковать разные навыки, проникнуть в давно заброшенные гробницы, обнаружить утраченные произведения магии, расшифровать старые фолианты, пройтись по незнакомым местам, или столкнуться с экзотическими
        существами. Барды любят сопровождать героев, чтобы засвидетельствовать их свершения из первых рук.<br> Бард, который может рассказать впечатляющую историю из личного опыта, зарабаты- вает известность среди других бардов. Более того, после повествования
        такого большого количества историй о великих свершениях героев, многие барды принимают их близко к сердцу и хотят принять роль героя сами.<br>

        <h3 style="text-align: center;">Создание барда</h3>
        Барды процветают за счет историй, не важно, правдивы они или нет. Ваша предыстория и мотивы не так важны, как истории, что ваш персонаж рассказывает о себе. Возможно, у вас было безопасное и ничем не примечательное детство. В нём нет хороших историй,
        чтобы поведать о них, но вы можете изобразить себя сиротой, воспитанным ведьмой на зловещем болоте. Или ваше детство действительно может быть достойным истории. Некоторые барды приобретают свою волшебную музыку необычайными способами, в том числе
        под влиянием фей или других сверхъестественных существ.<br> Были ли вы учеником у мастера, следуя за более опытным бардом, пока не начали следовать своему собственному пути? Или посещали коллегию, где вы обучались знаниям бардов и практиковали
        свою музыкальную магию? Может быть, вы в молодости сбежали из дома, или став сиротой подружились с бродячим бардом, который стал вашим наставником. Или вы могли быть избалованным знатным ребенком, обученным мастером.<br>

        <h3 style="text-align: center;">Быстрое создание</h3>
        Вы можете быстро создать барда, следуя этим рекомендациям.<br> Во-первых, у вашей Харизмы должно быть наивысшее значение. Следующей по величине характеристикой должна быть Ловкость.<br> Во-вторых, выберите предысторию «Артист».<br> В-третьих,
        получите заговоры злая насмешка и пляшущие огоньки вместе со следующими заклинаниями 1 уровня: волна грома, лечащее слово, обнаружение магии и очарование личности.<br>

        <h3 style="text-align: center;">Хиты</h3>
        <b>Кость Хитов:</b> 1к8 за каждый уровень<br>
        <b>Хиты на 1 уровне</b>: 8 + ваш модификатор Телосложения<br>
        <b>Хиты на следующих уровнях:</b> 1к8 (или 4) модификатор Телосложения за каждый уровень после первого<br>
        <h3 style="text-align: center;">Владение</h3>
        <b>Доспехи:</b> Лёгкие доспехи<br>
        <b>Оружие:</b> Простое оружие, длинные мечи, короткие мечи, рапиры, ручные арбалеты<br>
        <b>Спаброски:</b> Ловкость, Харизма<br>
        <b>Навыки:</b> Выберите 3 навыка из следующих: Атлетика, Акробатика, Лoвкость рук, Скрытность, Магия, История, Анализ, Природа, Религия, Уход за животными, Проницательность, Медицина, Внимательность, Выживание, Обман, Запугивание, Выступление,
        Убеждение
        <br>
        <h3 style="text-align: center;">Снаряжение</h3>
        Вы начинаете со следующим снаряжением в дополнение к снаряжению, полученному за вашу предысторию:<br> а) рапира, б) длинный меч или в) любое простое оружие<br> а) набор дипломата или б) набор артиста<br> а) лютня или б) любой другой музыкальный
        инструмент
        <br> Кожаный доспех и кинжал<br>
        <h3>Умения</h3>
        <b>ВДОХНОВЕНИЕ БАРДА</b> Своими словами или музыкой вы можете вдохновлять других. Для этого вы должны бонусным действием выбрать одно существо, отличное от вас, в пределах 60 футов, которое может вас слышать.<br> Это существо получает кость бардовского
        вдохновения — к6.<br> В течение следующих 10 минут это существо может один раз бросить эту кость и добавить результат к проверке характеристики, броску атаки или спасброску, который оно совершает. Существо может принять решение о броске кости
        вдохновения уже после броска к20, но должно сделать это прежде, чем Мастер объявит результат броска. Как только кость бардовского вдохновения брошена, она исчезает. Существо может иметь только одну такую кость одновременно.<br> Вы можете использовать
        это умение количество раз, равное модификатору вашей Харизмы, но как минимум один раз. Потраченные использования этого умения восстанавливаются после продолжительного отдыха.<br> Ваша кость бардовского вдохновения изменяется с ростом вашего уровня
        в этом классе. Она становится к8 на 5 уровне, к10 на 10 уровне и к12 на 15 уровне.<br>

        <b>МАСТЕР НА ВСЕ РУКИ</b> Начиная со 2 уровня вы можете добавлять половину бонуса мастерства, округлённую в меньшую сторону, ко всем проверкам характеристик, куда этот бонус ещё не включён.<br>

        <b>ПЕСНЬ ОТДЫХА</b> Начиная со 2 уровня вы с помощью успокаивающей музыки или речей можете помочь своим раненым союзникам восстановить их силы во время короткого отдыха.<br> Если вы, или любые союзные существа, способные слышать ваше исполнение,
        восстанавливаете хиты в конце короткого отдыха, каждый из вас восстанавливает дополнительно 1к6 хитов. Для того, чтобы восстановить дополнительные хиты, существо должно потратить в конце короткого отдыха как минимум одну Кость Хитов.<br>

    </div>
    {%endblock content%}

wiki/templates/wiki/content.html
{%extends "wiki/base.html" %}
    {%block content%}
    <div class="text_field">
        <div class="text_field_con">
        <h1>Новости</h1>
        <div class="text_1">
            <div class="text_1foto">
            </div>
            <div class="text_1text">
                <b>Заклинания:</b>
                <b>Солнечный ожог (Sunburst)</b><br> Яркий солнечный свет освещает всё в 60-футовом радиусе с центром на точке, выбранной вами в пределах дистанции. Все существа, находящиеся в нём, должны совершить спасбросок Телосложения...
            </div>
        </div>
        <div class="text_2">
            <div class="text_2foto">
            </div>
            <div class="text_2text">
                <b>Заклинания:</b>
                <b>Священное оружие (Holy weapon)</b><br> Вы наполняете оружие, которого касаетесь, святой силой. Пока заклинание активно, оружие излучает яркий свет в радиусе 30 фт. и тусклый свет в пределах еще 30 фт. Кроме того, атаки, совершенные
                этим оружием, наносят дополнительный урон излучением 2d8 при попадании...
            </div>
        </div>
        <div class="text_3">
            <div class="text_3foto">
            </div>
            <div class="text_3text">
                <b>Классы:</b>
                <b>БАРД (Bard)</b><br> Напевая, и перебирая пальцами по старинному монументу, найденному в заброшенных руинах, полуэльфийка в обветшалом кожаном доспехе перебирает знания, мелькающие в её голове, вызывая силой магии, заключённой в песне,
                людей, которые построили этот монумент и загадочное предание, которое он изображает...
            </div>
        </div>
        <div class="text_4">
            <div class="text_4foto">
            </div>
            <div class="text_4text">
                <b>Расы:</b>
                <b>Пентадрон</b><br> Модроны— создания абсолютного порядка, поддерживающие в своем обществе иерархию как в пчелином улье. Они обитают на плане Механус, и следят за его вечно вращающимися шестернями, ведя идеально упорядоченное существование
                механических аппаратов.<br> Абсолютный закон и порядок. Под управлением своего лидера, Праймуса, модроны стараются...

            </div>
        </div>
        <div class="text_5">
            <div class="text_5foto">
            </div>
            <div class="text_5text">
                <b>Предметы:</b>
                <b>Безделушки</b><br>
                <b>1—</b> Мумифицированная рука гоблина<br>
                <b>2—</b> Кусочек кристалла, слабо светящийся в лунном свете<br>
                <b>3—</b> Золотая монета, отчеканенная в неизвестной стране<br>
                <b>4—</b> Дневник, написанный на неизвестном вам языке<br>
                <b>5—</b> Латунное кольцо, которое не темнеет со временем...<br>
            </div>
        </div>
        <div class="text_6">
            <div class="text_6foto">
            </div>
            <div class="text_6text">
                <b>Бестиарий:</b>
                <b>Драук</b><br> Когда дроу подает большие надежды, Лолс призывает его в Ямы Демонической Паутины, чтобы испытать его веру и силу. Те, кто проходят испытание, возвышаются пред Лолс. Те же, кто не преуспеет, превращаются в драуков — ужасных
                гибридов дроу и гигантских пауков, которые служат живым напоминанием мощи Лолс. Лишь дроу может быть обращен в драука, и секретом такого превращения владеет только Лолс...
            </div>
        </div>
        <div class="text_7">
            <div class="text_7foto">
            </div>
            <div class="text_7text">
                <b>Оружие:</b>
                <b>Воинское рукопашное</b><br>
                <b>Алебарда</b><br>
                <b>Стоимость:</b> 20 зм<br>
                <b>Урон:</b> 1d20 рубящий...
            </div>
        </div>
        </div>
    </div>
    {%endblock content%}

wiki/templates/wiki/contents.html
{%extends "wiki/base.html" %}
    {%block content%}
    <div class="text_field">
        <div class="text_field_con">
        <h1>Новости</h1>
        <div class="text_1">
            <div class="text_1foto">
            </div>
            <div class="text_1text">
                <b>Заклинания:</b>
                <b>Солнечный ожог (Sunburst)</b><br> Яркий солнечный свет освещает всё в 60-футовом радиусе с центром на точке, выбранной вами в пределах дистанции. Все существа, находящиеся в нём, должны совершить спасбросок Телосложения...
            </div>
        </div>
        <div class="text_2">
            <div class="text_2foto">
            </div>
            <div class="text_2text">
                <b>Заклинания:</b>
                <b>Священное оружие (Holy weapon)</b><br> Вы наполняете оружие, которого касаетесь, святой силой. Пока заклинание активно, оружие излучает яркий свет в радиусе 30 фт. и тусклый свет в пределах еще 30 фт. Кроме того, атаки, совершенные
                этим оружием, наносят дополнительный урон излучением 2d8 при попадании...
            </div>
        </div>
        <div class="text_3">
            <div class="text_3foto">
            </div>
            <div class="text_3text">
                <b>Классы:</b>
                <b>БАРД (Bard)</b><br> Напевая, и перебирая пальцами по старинному монументу, найденному в заброшенных руинах, полуэльфийка в обветшалом кожаном доспехе перебирает знания, мелькающие в её голове, вызывая силой магии, заключённой в песне,
                людей, которые построили этот монумент и загадочное предание, которое он изображает...
            </div>
        </div>
        <div class="text_4">
            <div class="text_4foto">
            </div>
            <div class="text_4text">
                <b>Расы:</b>
                <b>Пентадрон</b><br> Модроны— создания абсолютного порядка, поддерживающие в своем обществе иерархию как в пчелином улье. Они обитают на плане Механус, и следят за его вечно вращающимися шестернями, ведя идеально упорядоченное существование
                механических аппаратов.<br> Абсолютный закон и порядок. Под управлением своего лидера, Праймуса, модроны стараются...

            </div>
        </div>
        <div class="text_5">
            <div class="text_5foto">
            </div>
            <div class="text_5text">
                <b>Предметы:</b>
                <b>Безделушки</b><br>
                <b>1—</b> Мумифицированная рука гоблина<br>
                <b>2—</b> Кусочек кристалла, слабо светящийся в лунном свете<br>
                <b>3—</b> Золотая монета, отчеканенная в неизвестной стране<br>
                <b>4—</b> Дневник, написанный на неизвестном вам языке<br>
                <b>5—</b> Латунное кольцо, которое не темнеет со временем...<br>
            </div>
        </div>
        <div class="text_6">
            <div class="text_6foto">
            </div>
            <div class="text_6text">
                <b>Бестиарий:</b>
                <b>Драук</b><br> Когда дроу подает большие надежды, Лолс призывает его в Ямы Демонической Паутины, чтобы испытать его веру и силу. Те, кто проходят испытание, возвышаются пред Лолс. Те же, кто не преуспеет, превращаются в драуков — ужасных
                гибридов дроу и гигантских пауков, которые служат живым напоминанием мощи Лолс. Лишь дроу может быть обращен в драука, и секретом такого превращения владеет только Лолс...
            </div>
        </div>
        <div class="text_7">
            <div class="text_7foto">
            </div>
            <div class="text_7text">
                <b>Оружие:</b>
                <b>Воинское рукопашное</b><br>
                <b>Алебарда</b><br>
                <b>Стоимость:</b> 20 зм<br>
                <b>Урон:</b> 1d20 рубящий...
            </div>
        </div>
        </div>
    </div>
    <div class="right_field"></div>
    {%endblock content%}

wiki/templates/wiki/items.html
{%extends "wiki/base.html" %}
    {%block content%}
    <div class="text_field">
        <h1 style="text-align: center;">Предметы</h1>
        <h2 style="text-align: center;">Безделушки</h2>
        <b>1—</b> Мумифицированная рука гоблина<br>
        <b>2—</b> Кусочек кристалла, слабо светящийся в лунном свете<br>
        <b>3—</b> Золотая монета, отчеканенная в неизвестной стране<br>
        <b>4—</b> Дневник, написанный на неизвестном вам языке<br>
        <b>5—</b> Латунное кольцо, которое не темнеет со временем<br>
        <b>6—</b> Старая стеклянная шахматная фигура<br>
        <b>7—</b> Пара игральных костей, у обеих вместо шестёрок нарисованы черепа<br>
        <b>8—</b> Небольшой идол, изображающий страшное чудовище, насылающий кошмары, когда вы спите рядом с ним<br>
        <b>9—</b> Верёвочное ожерелье, на котором висят четыре мумифицированных эльфийских пальца<br>
        <b>10—</b> Квитанция для получения посылки в неизвестном вам королевстве<br>
        <b>11—</b> 30-граммовый кусочек неизвестного материала<br>
        <b>12—</b> Маленькая тряпичная кукла, утыканная иголками<br>
        <b>13—</b> Зуб неизвестного зверя<br>
        <b>14—</b> Огромная чешуйка, возможно, драконья<br>
        <b>15—</b> Ярко-зелёное перо<br>
        <h2 style="text-align: center;">Доспехи и щиты</h2>
        <h3 style="text-align: center;">Средние доспехи</h3>
        <b>Шкурный</b><br>
        <b>Стоимость:</b> 10 зм.<br>
        <b>Класс доспеха:</b> 12 + модификатор ЛОВ (макс. 2)<br>
        <b>Сила:</b> -<br>
        <b>Скрытность:</b> -<br>
        <b>Вес:</b> 12 фнт.<br>
        <h3 style="text-align: center;">Щит</h3>
        <b>Стоимость:</b> 10 зм.<br>
        <b>Класс доспеха:</b> +2<br>
        <b>Сила:</b> -<br>
        <b>Скрытность:</b> -<br>
        <b>Вес:</b> 6 фнт.<br>
        <h3 style="text-align: center;">Драгоценные камни</h3>
        <b>Гагат</b> (непрозрачный, чёрный, 100 зм)
        <h3 style="text-align: center;">Инструменты</h3>
        <h4 style="text-align: center;">Музыкальные</h4>
        <b>Лютня</b><br>
        <b>Стоимость:</b> 35 зм<br>
        <b>Вес:</b> 3 фнт.<br>
        <h3 style="text-align: center;">Монеты (деньги)</h3>
        <b>Золотые</b><br>
        <h3 style="text-align: center;">Оружие</h3>
        <h4 style="text-align: center;">Воинское рукопашное</h4>
        <b>Алебарда</b><br>
        <b>Стоимость:</b> 20 зм<br>
        <b>Урон:</b> 1d20 рубящий<br>
        <b>Вес:</b> 6 фнт<br>
        <b>Свойства:</b> двуручное, досягаемость, тяжёлое<br>
        <h3 style="text-align: center;">Произведения искусства</h3>
        <b>Большой золотой браслет</b><br>
        <b>Стоимость:</b> 250 зм<br>
        <h3 style="text-align: center;">Снаряжение</h3>
        <h4 style="text-align: center;">Боеприпасы</h4>
        <b>Ведро</b><br>
        <b>Стоимость:</b> 5 мм<br>
        <b>Вес:</b> 2 фнт<br>
        <h3 style="text-align: center;">Сокровищница</h3>
        <b>Драгоценный камень</b>, стоимостью 100 зм.
    </div>
    {%endblock content%}

wiki/templates/wiki/race.html
{% extends 'wiki/base.html' %}

{% block content %}
    {% for race in races %}
        <tr>
            {% for field, value in race.fields.items %}
                <td>{{ field }} : {{ value }}</td>
            {% endfor %}
        </tr>
    {% empty %}
        No races have been added yet
    {% endfor %}
{% endblock %}